import Mathlib

import Intuitionism.fin_seq
import Intuitionism.IPC

/-!
# Spread and fan infrastructure

This file packages the spread/fan language used in paper §3.1 and the bar/fan
reasoning used later in §4.1 and §4.3.

Some notions here are Lean-level proof infrastructure rather than literal items
from the paper.  Whenever that happens, the comments state explicitly which part
of Veldman's argument they are supporting.
-/

open NatSeq
open fin_seq

/-- Spread law (denoted `E : Seq → {0,1}` in the paper, and `E(a)=0` means “admitted”).
    Here we use `σ : fin_seq → ℕ` and encode “admitted” by `σ s = 0`, essentially relaxing `{0,1}`
    to `ℕ` via the 0/nonzero distinction.
    We also include the standard “extendability” characterization of a spread law:
    `σ s = 0 ↔ ∃ n, σ (s⋆n) = 0`. -/
def is_spread_law (σ : fin_seq → ℕ) : Prop :=
  σ empty_seq = 0 ∧
    (∀ s : fin_seq, σ s = 0 ↔ ∃ n : ℕ, σ (extend s (singleton n)) = 0)

/-- Fan law:
    The paper does not give a separate definition of “fan law”, but §3.1 mentions the binary fan,
    and §4.1 uses the fan theorem to extract a uniform bound on a (sub)fan.
    Here we define a fan law as: a spread law + a uniform bound on branching at each node
    (locally finite branching, bounded). -/
def is_fan_law (β : fin_seq → ℕ) : Prop :=
  is_spread_law β ∧
    (∀ s : fin_seq,
      (β s = 0 → ∃ n : ℕ, ∀ m : ℕ, β (extend s (singleton m)) = 0 → m ≤ n))

/-- This is purely extracting the first component of `is_fan_law` (fan ⇒ spread). -/
lemma fan_law_is_spread_law (β : fin_seq → ℕ) (hβ : is_fan_law β) : is_spread_law β :=
  hβ.1

/-- The spread generated by a spread law (its elements are infinite sequences `a` such that all
    finite initial segments are admitted):
    if `∀ n, E(a↾n) = 0` then we write `a ∈ E`. Here `finitize a n` plays the role of `a↾n`. -/
def spread (σ : fin_seq → ℕ) (_hσ : is_spread_law σ) : Type :=
  { a : 𝒩 // ∀ n : ℕ, σ (finitize a n) = 0 }

/-- fan: again an infinite sequence with every initial segment admitted, but the law is stronger
    (a fan law).
    In the paper one often uses the fan theorem on some subfan to obtain a uniform bound. -/
def fan (β : fin_seq → ℕ) (_hβ : is_fan_law β) : Type :=
  { a : 𝒩 // ∀ n : ℕ, β (finitize a n) = 0 }

/-- In Lean, `fan` and `spread` differ only in the proof argument; the subtype predicate is the same,
    hence they are definitionally equal (`rfl`). -/
lemma fan_is_spread (β : fin_seq → ℕ) (hβ : is_fan_law β) :
    fan β hβ = spread β (fan_law_is_spread_law β hβ) := by
  rfl

/-- The notion of a bar:
    In the proof of Lemma 4.1, on a (sub)fan the paper obtains something like
    “for every path there exists a stage hitting some property”, and then uses the fan theorem
    to extract a uniform bound.
    `is_bar` is exactly the formalization of “every path hits the set `B`”. -/
def is_bar (β : fin_seq → ℕ) (hβ : is_fan_law β) (B : Set fin_seq) : Prop :=
  ∀ a : fan β hβ, ∃ n : ℕ, finitize a.1 n ∈ B



/-- The complementary law `Γ`/`F` from paper §3.1, represented as a finite set of formulas at each node.
In the paper the codomain is finite subsets of `Sent`; here we work in the propositional fragment,
so the codomain is finite subsets of `IPC.Form`. -/
abbrev CompLaw (_ : fin_seq → ℕ) := fin_seq → Finset IPC.Form

/-- Initial segment (prefix) relation:
    `Prefix s t` means “`s` is an initial segment of `t`” (corresponding to the paper with `b = t`,
    `a = s`). -/
def Prefix (s t : fin_seq) : Prop :=
  ∃ h : s.len ≤ t.len,
    ∀ i : Fin s.len, s.seq i = t.seq (Fin.castLE h i)

/-- Monotonicity of the complementary law (only required on admitted nodes): -/
def MonotoneOnAdmitted (σ : fin_seq → ℕ) (F : CompLaw σ) : Prop :=
  ∀ {s t : fin_seq},
    Prefix s t →
    σ s = 0 → σ t = 0 →
    F s ⊆ F t

/-- Standard bar induction principle (a common “fan/bar” reasoning schema):
    the paper actually uses the fan theorem (§4.1 “using the fan theorem”) and does not state
    bar induction in this form. -/
def principle_of_bar_induction_std
    (β : fin_seq → ℕ) (hβ : is_fan_law β) (B : Set fin_seq) (_ : is_bar β hβ B)
    (C : Set fin_seq) (_ : B ⊆ C)
    (_ :
      ∀ s : fin_seq,
        β s = 0 →
          (∀ n : ℕ, β (extend s (singleton n)) = 0 → (extend s (singleton n)) ∈ C) →
            s ∈ C)
    : Prop :=
  empty_seq ∈ C

open fin_seq

/-- Extract `s.len ≤ t.len` from `Prefix s t` (a pure Lean helper lemma). -/
lemma Prefix_len_le {s t : fin_seq} (h : Prefix s t) : s.len ≤ t.len := by
  rcases h with ⟨hle, _⟩
  exact hle

/-- Given that `s` is a prefix of `t`, package the “remaining part” as a `fin_seq`:
    this corresponds to the paper’s frequent use of notation like `t = s * r` (or `b = a * q`)
    for extensions, but here it is implemented explicitly. -/
def suffix (s t : fin_seq) (hle : s.len ≤ t.len) : fin_seq :=
  ⟨t.len - s.len, fun j =>
      t.seq ⟨j.val + s.len, by
        -- j.val + s.len < t.len
        have hj : j.val + s.len < (t.len - s.len) + s.len :=
          Nat.add_lt_add_right j.isLt s.len
        -- (t.len - s.len) + s.len = t.len
        simpa [Nat.sub_add_cancel hle] using hj
      ⟩⟩

/-- An ext lemma avoiding HEq: compare `seq` after casting the index when lengths are equal
    (a pure Lean helper lemma). -/
lemma ext_cast {a b : fin_seq}
    (hlen : a.len = b.len)
    (hseq : ∀ i : Fin a.len, a.seq i = b.seq (Fin.cast hlen i)) :
    a = b := by
  cases a with
  | mk al as =>
    cases b with
    | mk bl bs =>
      cases hlen
      -- now goal reduces to equality of functions Fin al → ℕ
      have : as = bs := by
        funext i
        simpa using (hseq i)
      cases this
      rfl

/-- Key “decomposition/reconstruction” lemma:
    if `Prefix s t`, then `extend s (suffix s t ...) = t`.
    This makes precise in Lean the intuition “prefix + remainder = original sequence”
    used throughout the paper. -/
lemma extend_suffix_eq_of_Prefix {s t : fin_seq} (h : Prefix s t) :
    extend s (suffix s t (Prefix_len_le h)) = t := by
  rcases h with ⟨hle, hseq⟩
  set r : fin_seq := suffix s t hle

  have hlen : (extend s r).len = t.len := by
    simp [fin_seq.extend, r, suffix, Nat.add_sub_of_le hle]

  apply ext_cast hlen
  intro i

  have hiLt : i.val < t.len := by
    simpa [hlen] using i.isLt

  have hcast :
      (Fin.cast hlen i : Fin t.len) = ⟨i.val, hiLt⟩ := by
    apply Fin.ext
    rfl

  by_cases hi : i.val < s.len
  · -- prefix part
    let iS : Fin s.len := ⟨i.val, hi⟩
    have hcastLE :
        (Fin.castLE hle iS : Fin t.len) = ⟨i.val, hiLt⟩ := by
      apply Fin.ext
      rfl

    -- LHS = s.seq iS
    have hL : (extend s r).seq i = s.seq iS := by
      simp [fin_seq.extend, hi, iS]

    -- RHS = t.seq (castLE ...) = s.seq iS by Prefix hypothesis
    have hR : t.seq ⟨i.val, hiLt⟩ = s.seq iS := by
      have := hseq iS
      -- this : s.seq iS = t.seq (Fin.castLE hle iS)
      -- rewrite castLE to ⟨i.val,hiLt⟩
      simpa [hcastLE] using this.symm

    -- combine, and replace RHS cast
    simp [hcast, hL, hR]

  · -- suffix part
    have hle2 : s.len ≤ i.val := Nat.le_of_not_lt hi
    have hsubadd : (i.val - s.len) + s.len = i.val := Nat.sub_add_cancel hle2

    have hL :
        (extend s r).seq i = t.seq ⟨i.val, hiLt⟩ := by
      -- unfold extend + suffix: becomes t.seq ⟨(i-s)+s, _⟩ then rewrite by hsubadd
      have :
          (extend s r).seq i
            =
          t.seq ⟨(i.val - s.len) + s.len, by
            simpa [hsubadd] using hiLt⟩ := by
        simp [fin_seq.extend, hi, r, suffix]
      -- rewrite index to i.val
      have hfin :
          (⟨(i.val - s.len) + s.len, by
              simpa [hsubadd] using hiLt⟩ : Fin t.len) = ⟨i.val, hiLt⟩ := by
        apply Fin.ext
        exact hsubadd
      simpa [hfin] using this

    simp [hcast, hL]

/-- Turn `Prefix s t` into “there exists `r` such that `t = extend s r`” (existential decomposition). -/
lemma Prefix_exists_extend {s t : fin_seq} (h : Prefix s t) :
    ∃ r : fin_seq, t = extend s r := by
  have hle : s.len ≤ t.len := Prefix_len_le h
  refine ⟨suffix s t hle, ?_⟩
  simpa [suffix] using (extend_suffix_eq_of_Prefix (s := s) (t := t) h).symm
